# Generated by Django 5.0.4 on 2024-05-09 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='название')),
                ('description', models.TextField(blank=True, max_length=1000, verbose_name='описании')),
                ('owner', models.CharField(max_length=10, verbose_name='автор книги')),
            ],
        ),
    ]
